# Testfile for REST Client Extension   -  https://github.com/Huachao/vscode-restclient
#
###
# 
@host_redmine_v4 = https://192.168.178.159
@host_redmine_v3 = https://192.168.178.158
@host = {{host_redmine_v4}}
###
#
@adminApiKey = 7dacec6e34261293843380d4aaf2252f1c8ca520
@userApiKey = aa0c98be0bbb6ed6d52a35cb704bae23b15b9990
@apikey = {{userApiKey}}
###
@testFileToken = 6.d64421f6202bc20daa927e069f2fe30912e5656ad78a1003733604db4c41d3d1
@testIssue = 1
@testProject = git-helloworld

###
GET {{host}}/users/current.json
X-Redmine-API-Key: {{apikey}}

###
GET {{host}}/users/1.json
X-Redmine-API-Key: {{apikey}}

###
# list all projects
#
GET {{host}}/projects.json
X-Redmine-API-Key: {{apikey}}

###
# list all issues in project
#
GET {{host}}/projects/{{testProject}}/issues.json
X-Redmine-API-Key: {{apikey}}

###
# upload the file 
# creates a file token
#
# @name PostFileUpload
POST {{host}}/uploads.json?filename=Unbenannt.PNG
X-Redmine-API-Key: {{apikey}}
Content-Type: application/octet-stream

< ./Unbenannt.PNG
 

###
# use the file from post request 'PostFileUpload'
# 
@newTokenid = {{PostFileUpload.response.body.$.upload.token}}
PUT {{host}}/issues/{{testIssue}}.json
X-Redmine-API-Key: {{apikey}}
Content-Type: application/json

{

  "issue": {
      "notes": "Der Kommentar mit Datei !Unbenannt.PNG!" ,
    "uploads": [
      {"token": "{{newTokenid}}", "filename": "Unbenannt.PNG", "content_type": "image/png"}
    ]
  }
}

###

POST http://192.168.178.163:12201/gelf

{"message_typ":"Testrequest", "short_message":"Hello there", "host":"example.org", "facility":"test", "_foo":"bar"}

###
@jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkhhcnJ5IEhhdGhvcm4iLCJlbWFpbCI6ImhhcnJ5QGRvbWFpbi5jb20iLCJiaXJ0aGRhdGUiOiIxOTIzLTEyLTEyIiwibmFtZWlkIjoiYjAwNmE3YjgtMDRlMy00M2E3LThkZjUtMjc2ZjVmZTFlNzQyIiwicm9sZSI6WyJHcmFuZHBhIl0sIm5iZiI6MTU3MzAzNTAxNCwiZXhwIjoxNTk1Njk3MDE0LCJpYXQiOjE1NzMwMzUwMTR9.49RDLXRfUZ1utXRioHFS6WkpqdlhZspLmhrIHH7Mjlk
GET https://localhost:5001/datenobjekt/2
Authorization: Bearer {{jwt}}

###
GET https://localhost:5001/datenobjekt/2

###
http://rappelkiste.dyndns.ddnss.de:5000

###
POST http://zentrale.schulz-home.com:5000/alfred

{
    "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
    "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8Pdd",
    "type": "url_verification"
}
}
